obj-$(CONFIG_PINCTRL_WCD) += pinctrl-wcd.o
obj-$(CONFIG_PINCTRL_LPI) += pinctrl-lpi.o
obj-$(CONFIG_SOUNDWIRE_WCD_CTRL) += swr-wcd-ctrl.o
obj-$(CONFIG_SOUNDWIRE) += regmap-swr.o
obj-$(CONFIG_SOUNDWIRE) += soundwire.o

