obj-$(CONFIG_WCD9XXX_CODEC_CORE) += wcd9xxx-rst.o wcd9xxx-core-init.o wcd9xxx-core.o wcd9xxx-irq.o wcd9xxx-slimslave.o wcd9xxx-utils.o wcd9335-regmap.o \
                                      wcd9335-tables.o msm-cdc-pinctrl.o msm-cdc-supply.o wcd934x/wcd934x-regmap.o wcd934x/wcd934x-tables.o
obj-$(CONFIG_SND_SOC_WCD9XXX_V2) += wcd9xxx-common-v2.o wcd9xxx-resmgr-v2.o wcdcal-hwdep.o wcd9xxx-soc-init.o wcd-dsp-utils.o wcd-dsp-mgr.o
obj-$(CONFIG_COMMON_CLK_QCOM) += audio-ext-clk-up.o
obj-$(CONFIG_COMMON_CLK_MSM) += audio-ext-clk.o
obj-$(CONFIG_SND_SOC_WCD9335) += wcd9335.o
obj-$(CONFIG_SND_SOC_WSA881X) += wsa881x.o wsa881x-tables.o wsa881x-regmap.o wsa881x-temp-sensor.o
obj-$(CONFIG_SND_SOC_WSA881X_ANALOG) += wsa881x-analog.o wsa881x-tables-analog.o wsa881x-regmap-analog.o
obj-$(CONFIG_SND_SOC_MSM_STUB) += msm_stub.o
obj-$(CONFIG_SND_SOC_WCD_SPI) += wcd-spi.o
obj-$(CONFIG_SND_SOC_WCD_CPE) += wcd_cpe_core.o wcd_cpe_services.o
obj-$(CONFIG_SND_SOC_WCD_MBHC) += wcd-mbhc-v2.o
obj-$(CONFIG_SND_SOC_WCD_MBHC_ADC) += wcd-mbhc-adc.o
obj-$(CONFIG_SND_SOC_WCD_MBHC_LEGACY) += wcd-mbhc-legacy.o
obj-$(CONFIG_SND_SOC_MSM_HDMI_CODEC_RX) += msm_hdmi_codec_rx.o
obj-$(CONFIG_SND_SOC_TFA9894) += tfa98xx-v6/
obj-y += wcd934x/
obj-y += sdm660_cdc/ 
obj-y += msm_sdw/

