obj-$(CONFIG_SND_SOC_ANALOG_CDC) += msm-analog-cdc.o sdm660-cdc-irq.o
obj-$(CONFIG_SND_SOC_DIGITAL_CDC) += msm-digital-cdc.o msm-digital-cdc-regmap.o
obj-$(CONFIG_SND_SOC_DIGITAL_CDC_LEGACY) += msm-digital-cdc-legacy.o msm-digital-cdc-legacy-regmap.o

